### ISSUE TITLE
RangeError: Wind Chill: temp must be <= (0C, 32F, 273.15K)

### ISSUE THREAD

**Issue by sumh** [strikeentco/feels#2]
> Node 8.9.1

hi there  
I follow the instruction and  use `windChill` class function ,I got this error 

```js
const Feels = require('feels');
let w = new Feels({temp:18,speed:4}).windChill();
console.log(w)

➜  weather git:(master) ✗ node index.js
/Users/Calvin/Her/her-op/node_modules/feels/lib/base.js:138
        throw new RangeError('Wind Chill: temp must be <= (0C, 32F, 273.15K)');
        ^

RangeError: Wind Chill: temp must be <= (0C, 32F, 273.15K)
    at Function.windChill (/Users/Calvin/Her/her-op/node_modules/feels/lib/base.js:138:15)
    at Feels.windChill (/Users/Calvin/Her/her-op/node_modules/feels/main.js:167:38)
    at Object.<anonymous> (/Users/Calvin/Her/her-op/lib/weather/index.js:97:38)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

the same error log when I explicitly assign the unit 

```js
const Feels = require('feels');

const config = {
    temp: 18,
    speed: 4,
    units: {
        temp: 'c',
        speed: 'mps',
    },
};

let w = new Feels(config).windChill();


➜  weather git:(master) ✗ node index.js
/Users/Calvin/Her/her-op/node_modules/feels/lib/base.js:138
        throw new RangeError('Wind Chill: temp must be <= (0C, 32F, 273.15K)');
        ^

RangeError: Wind Chill: temp must be <= (0C, 32F, 273.15K)
    at Function.windChill (/Users/Calvin/Her/her-op/node_modules/feels/lib/base.js:138:15)
    at Feels.windChill (/Users/Calvin/Her/her-op/node_modules/feels/main.js:167:38)
    at Object.<anonymous> (/Users/Calvin/Her/her-op/lib/weather/index.js:107:27)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

```

**Comment by sumh** [comment]
Didn't notice temp must lower than 0, close this issue 

> Note: The humidex is used for temperatures less than 0 Celsius.
